# Generated by Django 4.2.6 on 2023-10-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_employermodel_options_employermodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employermodel',
            name='time_work',
            field=models.CharField(choices=[('Full-time job', 'Full-time job'), ('Part-time job', 'Part-time job')], default='Full-time job', max_length=15),
        ),
    ]
