# Generated by Django 4.2.6 on 2023-11-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_employermodel_time_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employermodel',
            name='main_programming_language',
            field=models.CharField(choices=[('1С', '1С'), ('C', 'C'), ('C#/.NET', 'C#/.NET'), ('C++', 'C++'), ('DB langs', 'DB langs'), ('Dart', 'Dart'), ('Golang', 'Golang'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Kotlin', 'Kotlin'), ('PHP', 'PHP'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Rust', 'Rust'), ('Scala', 'Scala'), ('Swift', 'Swift'), ('TypeScript', 'TypeScript'), ('N/A', 'N/A')], default='Python', max_length=15),
        ),
        migrations.AlterField(
            model_name='employermodel',
            name='required_english',
            field=models.CharField(choices=[('A1/Elementary', 'A1/Elementary'), ('A1+/Elementary+', 'A1+/Elementary+'), ('A2/Pre Intermediate', 'A2/Pre Intermediate'), ('A2+/Pre intermediate+', 'A2+/Pre intermediate+'), ('B1/Intermediate', 'B1/Intermediate'), ('B1+/Intermediate+', 'B1+/Intermediate+'), ('B2/Upper-intermediate', 'B2/Upper-intermediate'), ('B2+/Upper-intermediate', 'B2+/Upper-intermediate'), ('C1/Advanced', 'C1/Advanced'), ('C1+/Advanced+', 'C1+/Advanced+'), ('C2/Proficiency', 'C2/Proficiency')], default='B1/Intermediate', max_length=30),
        ),
        migrations.AlterField(
            model_name='employermodel',
            name='type_of_job',
            field=models.CharField(choices=[('Intern/Trainee Software Engineer', 'Intern/Trainee Software Engineer'), ('Junior Software Engineer', 'Junior Software Engineer'), ('Junior+ Software Engineer', 'Junior+ Software Engineer'), ('Middle Software Engineer', 'Middle Software Engineer'), ('Middle+ Software Engineer', 'Middle+ Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('SE Team/Tech Lead', 'SE Team/Tech Lead'), ('System Architect', 'System Architect'), ('Intern/Trainee QA', 'Intern/Trainee QA'), ('Junior QA', 'Junior QA'), ('Junior+ QA', 'Junior+ QA'), ('Middle QA', 'Middle QA'), ('Middle+ QA', 'Middle+ QA'), ('Senior QA', 'Senior QA'), ('QA Team/Tech Lead', 'QA Team/Tech Lead'), ('QA Manager', 'QA Manager'), ('DevOps', 'DevOps'), ('HTML Coder', 'HTML Coder'), ('Security Specialist', 'Security Specialist'), ('Delivery Manager', 'Delivery Manager'), ('Product Manager', 'Product Manager'), ('Product Owner', 'Product Owner'), ('Program Manager', 'Program Manager'), ('Project Manager', 'Project Manager'), ('Data Scientist', 'Data Scientist'), ('Data/Big Data Engineer', 'Data/Big Data Engineer'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Business Analyst', 'Business Analyst'), ('Data Analyst', 'Data Analyst'), ('Product Analyst', 'Product Analyst'), ('System Analyst', 'System Analyst')], default='Intern/Trainee Software Engineer', max_length=40),
        ),
    ]
