# Generated by Django 4.2.6 on 2023-11-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_employermodel_main_programming_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employermodel',
            options={'ordering': ('-timestamp', '-name_of_job'), 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
