# Generated by Django 4.2.6 on 2023-11-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storymodel',
            old_name='Headline',
            new_name='headline',
        ),
    ]
