# Generated by Django 4.2.6 on 2023-11-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_rename_for_who_storymodel_for_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='title',
            field=models.TextField(verbose_name='Title of story'),
        ),
    ]
