# Generated by Django 4.2.6 on 2023-11-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_commentmodel_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='storymodel',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='storymodel',
            name='for_who',
            field=models.CharField(choices=[('employers', 'employers'), ('employees', 'employees'), ('for everyone', 'for everyone')], default='for everyone', max_length=20, verbose_name='Useful for whom'),
        ),
    ]
