# Generated by Django 4.2.6 on 2023-11-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_storymodel_for_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='for_who',
            field=models.CharField(choices=[('employers', 'Employers'), ('employees', 'Employees'), ('everyone', 'Everyone')], default='everyone', max_length=20, verbose_name='Useful for whom'),
        ),
    ]
