# Generated by Django 4.2.6 on 2023-11-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_alter_storymodel_for_who'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storymodel',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
