# Generated by Django 4.2.6 on 2023-12-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_alter_storymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
