# Generated by Django 4.2.6 on 2023-10-31 20:03

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=employee.models.get_path_to_img, width_field='width_field'),
        ),
    ]
