# Generated by Django 4.2.6 on 2023-11-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeemodel_level_of_english_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemodel',
            options={'ordering': ('-timestamp', 'name'), 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
    ]
