# Generated by Django 4.2.6 on 2023-12-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employeemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='desired_salary',
            field=models.PositiveSmallIntegerField(default='500'),
        ),
    ]
